=== aminata054/projet-xml/whatsapp.dtd
<!ELEMENT whatsapp (discussions)>
<!ELEMENT discussions (contacts, groupes)>
<!ELEMENT contacts (contact*)>
<!ELEMENT contact (prenom, nom, numero_telephone, photo_profile, status, messages?)>
<!ATTLIST contact id NMTOKEN #REQUIRED>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT numero_telephone (#PCDATA)>
<!ELEMENT photo_profile (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT groupes (groupe*)>
<!ELEMENT groupe (nom_groupe, photo_groupe, admin, membres, messages?)>
<!ATTLIST groupe id NMTOKEN #REQUIRED>
<!ELEMENT nom_groupe (#PCDATA)>
<!ELEMENT photo_groupe (#PCDATA)>
<!ELEMENT admin EMPTY>
<!ATTLIST admin ref NMTOKEN #REQUIRED>
<!ELEMENT membres (membre*)>
<!ELEMENT membre EMPTY>
<!ATTLIST membre ref NMTOKEN #REQUIRED>
<!ELEMENT messages (message*)>
<!ELEMENT message (contenu, cite?, tag?, message_info)>
<!ATTLIST message
    id NMTOKEN #REQUIRED
    type (texte|vocal|fichier) #REQUIRED
    expediteur NMTOKEN #REQUIRED
    destinataire NMTOKEN #IMPLIED>
<!ELEMENT contenu (#PCDATA)>
<!ELEMENT cite (#PCDATA)>
<!ATTLIST cite ref NMTOKEN #IMPLIED>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT message_info EMPTY>
<!ATTLIST message_info
    heure CDATA #REQUIRED
    statut CDATA #IMPLIED>

=== aminata054/projet-xml/backups/whatsapp_backup_2025-07-15_20-36-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE whatsapp SYSTEM "whatsapp.dtd">
<whatsapp>
  <discussions>
    <contacts>
      <contact id="1">
        <nom>Diagne</nom>
        <prenom>Yacine fall</prenom>
        <numero_telephone>77123456789</numero_telephone>
        <photo_profile>images/contact_1_1752600097.jpg</photo_profile>
        <status>Hors ligne</status>
        <messages>
          <message id="1" type="texte" expediteur="1" destinataire="2">
            <contenu>Bonjour Yacine !</contenu>
            <message_info heure="2025-07-10T10:15:00" statut="double check"/>
          </message>
          <message id="2" type="texte" expediteur="2" destinataire="1">
            <contenu>Coucou Amina !</contenu>
            <cite ref="1"/>
            <message_info heure="2025-07-10T10:18:10" statut="lu"/>
          </message>
          <message id="10" type="texte" expediteur="1" destinataire="2">
            <contenu>comment tu vas ?</contenu>
            <message_info heure="2025-07-10T21:45:47" statut="double check"/>
          </message>
        </messages>
      </contact>
      
      <contact id="2">
        <nom>Sylla</nom>
        <prenom>Dié</prenom>
        <numero_telephone>987654321</numero_telephone>
        <photo_profile>images/image.png</photo_profile>
        <status>Hors ligne</status>
        <messages>
          <message id="3" type="texte" expediteur="1" destinataire="2">
            <contenu>Coucou Dié !</contenu>
            <message_info heure="2025-07-10T09:18:00" statut="envoye"/>
          </message>
          <message id="4" type="texte" expediteur="2" destinataire="1">
            <contenu>Salut Amina, comment tu vas</contenu>
            <cite ref="3"/>
            <message_info heure="2025-07-10T09:18:30" statut="double check"/>
          </message>
        </messages>
      </contact>
      
      <contact id="3">
        <nom>Ba</nom>
        <prenom>Marie</prenom>
        <numero_telephone>4225485</numero_telephone>
        <photo_profile>images/image.png</photo_profile>
        <status>En ligne</status>
        <messages>
          <message id="11" type="texte" expediteur="1" destinataire="3">
            <contenu>coucou</contenu>
            <message_info heure="2025-07-10T22:29:48" statut="double check"/>
          </message>
        </messages>
      </contact>
      
      <contact id="4">
        <nom>Cruz</nom>
        <prenom>Zahra</prenom>
        <numero_telephone>771234567</numero_telephone>
        <photo_profile>images/contact_4_1752600164.jpg</photo_profile>
        <status>Hors ligne</status>
        <messages/>
      </contact>
      
      <contact id="5">
        <nom>Sané</nom>
        <prenom>Alioune</prenom>
        <numero_telephone>781234567</numero_telephone>
        <photo_profile>images/image.png</photo_profile>
        <status>En ligne</status>
        <messages/>
      </contact>
      
      <contact id="6">
        <nom>Gueye</nom>
        <prenom>Assane</prenom>
        <numero_telephone>761234567</numero_telephone>
        <photo_profile>images/image.png</photo_profile>
        <status>Hors ligne</status>
        <messages/>
      </contact>
    </contacts>
    
    <groupes>
      <groupe id="1">
        <nom_groupe>Projet XML</nom_groupe>
        <photo_groupe>images/groupe.png</photo_groupe>
        <membres>
          <contact id="1">
            <nom>Sow</nom>
            <prenom>Tidiane</prenom>
            <numero_telephone>123456789</numero_telephone>
            <photo_profile>tidiane.jpg</photo_profile>
            <status>En ligne</status>
          </contact>
          <contact id="2">
            <nom>Sané</nom>
            <prenom>Alioune</prenom>
            <numero_telephone>987654321</numero_telephone>
            <photo_profile>alioune.jpg</photo_profile>
            <status>Hors ligne</status>
          </contact>
        </membres>
        <admin ref="1"/>
        <messages>
          <message id="5" type="texte" expediteur="1">
            <contenu>Salut tout le monde!</contenu>
            <message_info heure="2025-07-27T09:16:00" statut="double check"/>
          </message>
          <message id="6" type="texte" expediteur="2">
            <contenu>Bonjour alioune!</contenu>
            <message_info heure="2025-07-27T09:14:00" statut="double check"/>
          </message>
          <message id="7" type="texte" expediteur="1">
            <contenu>salut</contenu>
            <message_info heure="2025-07-12T23:17:49" statut="double check"/>
          </message>
          <message id="8" type="texte" expediteur="2">
            <contenu>bonjour tout le monde</contenu>
            <message_info heure="2025-07-14T16:51:00" statut="double check"/>
          </message>
          <message id="9" type="texte" expediteur="1">
            <contenu>oui</contenu>
            <message_info heure="2025-07-10T21:45:28" statut="double check"/>
          </message>
        </messages>
      </groupe>
    </groupes>
  </discussions>
</whatsapp>

=== aminata054/projet-xml/backups/whatsapp_backup_2025-07-22_02-02-23.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE whatsapp SYSTEM "whatsapp.dtd">
<whatsapp>
  <discussions>
    <contacts>
      <contact id="1">
        <nom>Diagne</nom>
        <prenom>Yacine fall</prenom>
        <numero_telephone>77123456789</numero_telephone>
        <photo_profile>images/68702812d3559-Capture d'écran 2025-06-08 233650.png</photo_profile>
        <status>Hors ligne</status>
        <messages>
          <message id="1" type="texte" expediteur="1" destinataire="2">
            <contenu>Bonjour Yacine !</contenu>
            <message_info heure="2025-07-10T10:15:00" statut="double check"/>
          </message>
          <message id="2" type="texte" expediteur="2" destinataire="1">
            <contenu>Coucou Amina !</contenu>
            <cite ref="1"/>
            <message_info heure="2025-07-10T10:18:10"/>
          </message>
        <message id="10" type="texte" expediteur="1" destinataire="1"><contenu>comment tu vas ?</contenu><message_info heure="2025-07-10T21:45:47" statut="double check"/></message><message id="12" type="texte" expediteur="1" destinataire="1"><contenu>oui</contenu><message_info heure="2025-07-22T00:36:28+02:00" statut="double check"/></message></messages>
      <numero/></contact>
      <contact id="2">
        <nom>sylla</nom>
        <prenom>Dié</prenom>
        <numero_telephone>987654321</numero_telephone>
        <photo_profile>images/image.png</photo_profile>
        <status>Hors ligne</status>
        <messages>
          <message id="3" type="texte" expediteur="1" destinataire="2">
            <contenu>Coucou Dié !</contenu>
            <message_info heure="2025-07-10T09:18:00"/>
          </message>
          <message id="4" type="texte" expediteur="2" destinataire="1">
            <contenu>Salut Amina, comment tu vas</contenu>
            <cite ref="3"/>
            <message_info heure="2025-07-10T09:18:30" statut="double check"/>
          </message>
        </messages>
      <numero/></contact>
    <contact id="3"><nom>ba</nom><prenom>marie</prenom><numero_telephone>4225485</numero_telephone><photo_profile>images/image.png</photo_profile><status>En ligne</status><messages><message id="11" type="texte" expediteur="1" destinataire="3"><contenu>coucou</contenu><message_info heure="2025-07-10T22:29:48" statut="double check"/></message><message id="15" type="texte" expediteur="1" destinataire="3"><contenu>bonsoir</contenu><message_info heure="2025-07-22T00:45:01+02:00" statut="double check"/></message></messages><numero>1457895</numero></contact><contact id="4"><prenom>Tidiane </prenom><nom>Sow</nom><numero_telephone/><status>Hors ligne</status><messages/><photo_profile>images/image.png</photo_profile></contact><contact id="5"><prenom>Alioune</prenom><nom>Sané</nom><numero_telephone/><status>En ligne</status><messages><message id="14" type="texte" expediteur="1" destinataire="5"><contenu>bonsoir</contenu><message_info heure="2025-07-22T00:42:19+02:00" statut="double check"/></message></messages><photo_profile>images/image.png</photo_profile></contact><contact id="6"><prenom>diatou</prenom><nom>ndiaye</nom><numero_telephone/><status>Hors ligne</status><messages/><photo_profile>images/image.png</photo_profile></contact><contact id="7"><prenom>maya</prenom><nom>drama</nom><numero_telephone/><status>Hors ligne</status><messages/><photo_profile>images/image.png</photo_profile></contact></contacts>
    <groupes>
      <groupe id="1">
        <nom_groupe>Projet XML</nom_groupe>
        <photo_groupe>images/groupe.png</photo_groupe>
        <membres>
          <contact id="1">
            <nom>Sow</nom>
            <prenom>Tidiane</prenom>
            <numero_telephone>123456789</numero_telephone>
            <photo_profile>tidiane.jpg</photo_profile>
            <status>En ligne</status>
          </contact>
          <contact id="2">
            <nom>Sané</nom>
            <prenom>Alioune</prenom>
            <numero_telephone>987654321</numero_telephone>
            <photo_profile>alioune.jpg</photo_profile>
            <status>Hors ligne</status>
          </contact>
        </membres>
        <admin ref="1"/>
        <messages>
          <message id="5" type="texte" expediteur="1">
            <contenu>Salut tout le monde!</contenu>
            <message_info heure="2025-07-27T09:16:00" statut="double check"/>
          </message>
          <message id="6" type="texte" expediteur="2">
            <contenu>Bonjour alioune!</contenu>
            <message_info heure="2025-07-27T09:14:00" statut="double check"/>
          </message>
          <message id="7" type="texte" expediteur="1">
            <contenu>salut</contenu>
            <message_info heure="2025-07-12T23:17:49" statut="double check"/>
          </message>
          <message id="8" type="texte" expediteur="2">
            <contenu>bonjour tout le monde</contenu>
            <message_info heure="2025-07-14T16:51:00" statut="double check"/>
          </message>
        <message id="9" type="texte" expediteur="1"><contenu>oui</contenu><message_info heure="2025-07-10T21:45:28" statut="double check"/></message><message id="13" type="texte" expediteur="1"><contenu>oui</contenu><message_info heure="2025-07-22T00:42:04+02:00" statut="double check"/></message></messages>
      </groupe>
    <groupe id="2"><nom_groupe>Test de groupe</nom_groupe><admin ref="2"/><membres><membre ref="1"/><membre ref="2"/><membre ref="3"/></membres><messages/><photo_groupe>images/group.png</photo_groupe></groupe></groupes>
  </discussions>
</whatsapp>
